# Generated by Django 5.0 on 2023-12-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_url',
            field=models.CharField(max_length=200, null=True, verbose_name='URL подтверждения'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='yoo_id',
            field=models.CharField(max_length=200, null=True, verbose_name='ID в YooKassa'),
        ),
    ]
