# Generated by Django 5.0 on 2024-01-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0001_initial'),
        ('shopping', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.order', verbose_name='Заказ'),
        ),
    ]
