# Generated by Django 5.0 on 2023-12-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта покупателя')),
                ('items_cost', models.IntegerField(default=0, verbose_name='Стоимость товаров')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_PAYMENT', 'Ожидает оплаты'), ('PAYED', 'Оплачен'), ('DELIVERY', 'В процессе доставки'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CREATED', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена единицы товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('image', models.FileField(blank=True, null=True, upload_to='items/', verbose_name='Изображение товара')),
                ('quantity_in_stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество товара на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shopping.OrderItem', to='shopping.product'),
        ),
    ]
