# Generated by Django 5.0 on 2023-12-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='id',
        ),
    ]
