# Generated by Django 5.0 on 2023-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_rename_uuid_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_PAYMENT', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('DELIVERY', 'В процессе доставки'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
