# Generated by Django 5.0 on 2023-12-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_order_email_order_session_key_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_cost',
        ),
    ]
